Game logic
meronogbai/tic-tac-toe pull request #3
Opened 2020-09-29 14:24 UTC by meronokbay

## Milestone 3: Game Logic

- Implemented methods and class using OOP 
- Added tic tac toe game logic

2020-09-29 17:30 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- The project uses at least two classes (Usually it uses three: Game, Board, and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- Please make use of `attr_readers/attr_writers`. Only use `attr_accessors` if you really need it. Please be aware that by using it you allow writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- Right now, player names can be an empty line, an integer and can be exactly the same as the other player. Please put a check to prevent all of these.

  #### Empty line

  ![image](https://user-images.githubusercontent.com/57726348/94592690-b4700900-02a6-11eb-90af-f9549c9b26f2.png)

  #### Integer name
  
  ![image](https://user-images.githubusercontent.com/57726348/94593079-ce115080-02a6-11eb-823e-deadb3c7e7bb.png)

  #### Duplicate names

  ![image](https://user-images.githubusercontent.com/57726348/94593488-e8e3c500-02a6-11eb-850e-0d62443642ec.png)

- There is a small bug in your game logic. The game continues even when the game is draw. Please fix this as well.

  ![image](https://user-images.githubusercontent.com/57726348/94594626-50017980-02a7-11eb-84be-64c099a7b01e.png)

**_I have left some comments below. Be sure to check them out._**

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-09-29 17:30 UTC, tirthajyoti-ghosh commented on lib/game_logic.rb
> +end
Please put these methods into a class.

2020-09-29 17:30 UTC, tirthajyoti-ghosh commented on lib/game_logic.rb
> +    puts "#{@seventh}|#{@eighth}|#{@ninth}"
Please remove all `puts` statements from files in `/lib` folder. No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-09-29 17:30 UTC, tirthajyoti-ghosh commented on lib/game_logic.rb
> +    @ninth = '   '
Having too many instance variables will slow down your application significantly. This is considered a bad practice. Only create an instance variable when you absolutely need it. 

There is a better solution to this problem. One possible solution could be using an array for storing token positions.

2020-09-30 09:04 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes.
Although it's working like a charm, there are some changes to do concerning your OOP implementation.

1. Split the different classes into many files with each only one class

2. Read the comment left below

Kindly, Make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +      @name = gets.chomp
Sorry but, `puts/gets` are not allowed in `lib` folder as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png)

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +  end
What is the aims of this method? It's never used anywhere?

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +    if (1..9).include?(move)
Why this line when there is the `validation(move)` method up there?

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +    end
It's preferable to return **constants integer** instead of string

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +    end
It's a good habit in programming to return constants integer instead of string

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +  end
It's a good habit in programming to return constants integer instead of string

2020-09-30 09:04 UTC, maelfosso commented on bin/main.rb
> +board = Board.new
A board exists because of the game. So you must have something like
```ruby
class Game 
  attr_reader board = Board.new
  attr_reader players...

 ....
end
```

2020-09-30 09:04 UTC, maelfosso commented on bin/main.rb
> +taken_fields = []
Instead of using this variable, kindly, please, directly update the `Board`

2020-09-30 09:04 UTC, maelfosso commented on lib/game_logic.rb
> +  end
It's too expensive.
What if you directly update the Game's Board after validating the move?
Something like this
```rb
if (1..9).include?(move)
      if taken_fields.include?(move)
        'Taken Field Error'
      else
       board.update(move, symbol)
      end
    else
      'No Integer Error'
    end
```

2020-09-30 14:26 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello  Meron Bsrat & Marco Erhardt** 
Great job following the improvements :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:  
We still need to fix a couple of details:

- [x] you have some puts in your player.rb file, output/input commands (puts, print, gets.chomp) should only be present in your main.rb file.
- [ ] In your main.rb file, use require_relative instead or require

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-09-30 16:27 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

Hey team :+1: 

Great job here. The code is short, readable, and works really well. :1st_place_medal: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-30 16:32 UTC, merged